utils::globalVariables(
    c(
        "%",
        ".",
        "FDR",
        "Levels",
        "Median+/-IQR",
        "N",
        "Variables",
        "f",
        "p",
        "p.value.signif",
        "stat",
        "Statistics",
        "value",
        "group1",
        "group2"
    )
)
